{{- if lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "felixconfigurations.projectcalico.org" }}
apiVersion: projectcalico.org/v3
kind: IPAMConfiguration
{{- else }}
apiVersion: crd.projectcalico.org/v1
kind: IPAMConfig
{{- end }}
metadata:
  name: default
spec:
  strictAffinity: {{ .Values.ipamConfig.strictAffinity }}
  autoAllocateBlocks: {{ .Values.ipamConfig.autoAllocateBlocks }}
