apiVersion: crd.projectcalico.org/v1
kind: IPAMConfig
metadata:
  name: rancher-config
spec:
  strictAffinity: {{ .Values.ipamConfig.strictAffinity }}
  autoAllocateBlocks: {{ .Values.ipamConfig.autoAllocateBlocks }}
