{{- if .Values.hub.apimanagement.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: apiportal
  namespace: {{ template "traefik.namespace" . }}
  labels:
  {{- include "traefik.labels" . | nindent 4 }}
spec:
  ports:
    - name: apiportal
      port: 9903
      protocol: TCP
      targetPort: apiportal
  selector:
  {{- include "traefik.labelselector" . | nindent 4 }}
{{- end -}}

