annotations:
  artifacthub.io/changes: |
    - "fix(ingressroute): :bug: use spec.ingressClassName with Proxy v3.7+"
    - "feat(provider/kubernetesIngressNGINX): set default values on httpentrypoint & httpsentrypoint"
    - "feat(deps): update traefik docker tag to v3.7.1"
    - "feat(api): support disableDashboardAd option"
    - "chore(release): publish 40.1.0"
  fleet.cattle.io/bundle-id: rke2
  traefik.io/hub-max-version: v3.20.1
  traefik.io/hub-min-version: v3.19.3
  traefik.io/proxy-max-version: v3.7.1
  traefik.io/proxy-min-version: v3.6.0
apiVersion: v2
appVersion: v3.7.1
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: https://raw.githubusercontent.com/traefik/traefik/master/docs/content/assets/img/traefik.logo.png
keywords:
- traefik
- ingress
- networking
kubeVersion: '>=1.25.0-0'
maintainers:
- email: michel.loiseleur@traefik.io
  name: mloiseleur
- email: remi.buisson@traefik.io
  name: darkweaver87
- name: jnoordsij
name: rke2-traefik
sources:
- https://github.com/traefik/traefik-helm-chart
- https://github.com/traefik/traefik
type: application
version: 40.1.005
