apiVersion: v1
name: rke2-canal-crd
description: Install CRDs for Canal Network Plugin.
version: v3.27.3-build20240423
appVersion: v3.27.3
keywords:
  - canal
sources:
  - https://github.com/rancher/rke2-charts
maintainers:
  - name: Rancher Labs
    email: charts@rancher.com
