annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: ServiceAccount now applies the `customLabels` field if set.
apiVersion: v2
appVersion: 1.12.2
description: CoreDNS is a DNS server that chains plugins and provides Kubernetes DNS
  Services
home: https://coredns.io
icon: https://coredns.io/images/CoreDNS_Colour_Horizontal.png
keywords:
- coredns
- dns
- kubedns
maintainers:
- name: mrueg
- name: haad
- name: hagaibarel
- name: shubham-cmyk
name: rke2-coredns
sources:
- https://github.com/coredns/coredns
type: application
version: 1.43.100
