---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: canal
  namespace: kube-system

{{ if .Values.calico.calicoKubeControllers }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-kube-controllers
  namespace: kube-system
{{ end }}
