url: https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-4.9.1/ingress-nginx-4.9.1.tgz
packageVersion: 00
# This repository does not use releaseCandidateVersions, so you can leave this as 00.
releaseCandidateVersion: 00
