url: https://charts.helm.sh/stable/packages/nginx-ingress-1.36.3.tgz
packageVersion: 02
# This repository does not use releaseCandidateVersions, so you can leave this as 00.
releaseCandidateVersion: 00
