url: https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-4.14.3/ingress-nginx-4.14.3.tgz
packageVersion: 03
# This repository does not use releaseCandidateVersions, so you can leave this as 00.
releaseCandidateVersion: 00
