url: https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-4.10.5/ingress-nginx-4.10.5.tgz
packageVersion: 02
# This repository does not use releaseCandidateVersions, so you can leave this as 00.
releaseCandidateVersion: 00
