url: https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-4.8.2/ingress-nginx-4.8.2.tgz
packageVersion: 00
# This repository does not use releaseCandidateVersions, so you can leave this as 00.
releaseCandidateVersion: 00
