url: https://github.com/k8snetworkplumbingwg/helm-charts.git
commit: ca7c0a7549952660eab8f4b12e7ec7be133b381c
subdirectory: whereabouts
packageVersion: 02
# whereabouts is only used as a dependency of multus
doNotRelease: true
