controller:
  enabled: true

  replicaCount: 1

  revisionHistoryLimit: 10

  args:
    leaderElection: true
    leaderElectionNamespace: "$(NAMESPACE)"
    httpEndpoint: ":8080"

  image:
    repository: rancher/mirrored-sig-storage-snapshot-controller
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  imagePullSecrets: []

  podAnnotations: {}

  podLabels: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  resources: {}

  nodeSelector:
    kubernetes.io/os: linux

  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/etcd"
      operator: "Exists"
      effect: "NoExecute"

  affinity: {}

  ## Ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
  ##
  pdb: {}

  topologySpreadConstraints: []

  rbac:
    # Specifies whether RBAC resources should be created
    create: true

  serviceAccount:
    # Specifies whether a ServiceAccount should be created
    create: true
    name: ""

  serviceMonitor:
    # Specifies whether a ServiceMonitor should be created
    create: false

  volumeSnapshotClasses: []
#    - name: linstor-csi-delete
#      annotations:
#        snapshot.storage.kubernetes.io/is-default-class: "true"
#      labels:
#        velero.io/csi-volumesnapshot-class: "true"
#      driver: linstor.csi.linbit.com
#      deletionPolicy: Delete

  priorityClassName: ""
    # Specifies wether a Priority Class should be attached to deployment pods

  # Change `hostNetwork` to `true` when you want the pod to share its host's network namespace.
  hostNetwork: false

  # DNS settings for the controller pod. https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
  dnsConfig: {}
  # DNS Policy for controller pod. For Pods running with hostNetwork, set to `ClusterFirstWithHostNet`
  # For further reference: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy.
  dnsPolicy: ClusterFirst

global:
  systemDefaultRegistry: ""
