url: local
workingDir: charts
packageVersion: 15
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: false
