url: https://github.com/piraeusdatastore/helm-charts.git
subdirectory: charts/snapshot-controller
commit: 100f3d3c3513e14b423093cbb1a6f8fdd38fafd1  # snapshot-controller-1.7.2
packageVersion: 02
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
