url: https://github.com/piraeusdatastore/helm-charts.git
subdirectory: charts/snapshot-controller
commit: ccc8a601db5ae518334da43ce7a5851ea349d526  # snapshot-controller-4.2.0
packageVersion: 01
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
