url: https://github.com/piraeusdatastore/helm-charts.git
subdirectory: charts/snapshot-controller
commit: caf8780858bdd5afe1d80fe2f559ca138f29740e  # snapshot-controller-4.0.0
packageVersion: 01
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
