url: https://github.com/piraeusdatastore/helm-charts.git
subdirectory: charts/snapshot-controller
commit: 79c15f2317860baf58fa70d00ff355a631a77206  # snapshot-controller-3.0.6
packageVersion: 00
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
