url: https://github.com/projectcalico/calico/releases/download/v3.31.3/tigera-operator-v3.31.3.tgz
packageVersion: 00
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
