url: https://github.com/projectcalico/calico/releases/download/v3.32.0/tigera-operator-v3.32.0.tgz
packageVersion: 00
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/projectcalico/calico/releases/download/v3.32.0/crd.projectcalico.org.v1-v3.32.0.tgz
