url: https://github.com/projectcalico/calico/releases/download/v3.30.0/tigera-operator-v3.30.0.tgz
packageVersion: 01
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
