url: https://github.com/projectcalico/calico/releases/download/v3.31.2/tigera-operator-v3.31.2.tgz
packageVersion: 01
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
