#!/bin/bash
set -e

cd "$(dirname "$0")"

CHARTS_BUILD_SCRIPT_VERSION=v1.9.25
CHARTS_BUILD_SCRIPT_ASSET=charts-build-scripts_linux_amd64

echo "Pulling in charts-build-scripts version ${CHARTS_BUILD_SCRIPT_VERSION}"

rm -rf ../bin
cd ..

mkdir -p ./bin
curl -fsSL \
	"https://github.com/rancher/charts-build-scripts/releases/download/${CHARTS_BUILD_SCRIPT_VERSION}/${CHARTS_BUILD_SCRIPT_ASSET}" \
	-o ./bin/charts-build-scripts
chmod +x ./bin/charts-build-scripts
./bin/charts-build-scripts --version