apiVersion: v2
appVersion: v3.32.0
description: Installs crd.projectcalico.org and operator.tigera.io Custom Resource
  Definitions (CRDs)
home: https://docs.tigera.io/calico
icon: https://docs.tigera.io/img/calico-logo.png
name: crd.projectcalico.org.v1
sources:
- https://github.com/projectcalico/calico/tree/master/charts/crd.projectcalico.org.v1
- https://github.com/tigera/operator
- https://github.com/projectcalico/calico
version: v3.32.000
