url: https://github.com/coredns/helm/releases/download/coredns-1.19.4/coredns-1.19.4.tgz
packageVersion: 02
# This repository does not use releaseCandidateVersions, so you can leave this as 00.
releaseCandidateVersion: 00
