{{- if and .Values.nodelocal.enabled .Values.nodelocal.use_cilium_lrp }}
apiVersion: "cilium.io/v2"
kind: CiliumLocalRedirectPolicy
metadata:
  name: "lrp-nodelocal"
spec:
  redirectFrontend:
    serviceMatcher:
      serviceName: {{ default (include "coredns.fullname" .) .Values.service.name }}
      namespace: {{ .Release.Namespace }}
      toPorts:
        - name: dns-tcp
          port: "53"
          protocol: TCP
        - name: dns
          port: "53"
          protocol: UDP 
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: node-local-dns
    toPorts:
      - name: dns
        port: "53"
        protocol: UDP
      - name: dns-tcp
        port: "53"
        protocol: TCP
{{- end }}
