name: CI-pullrequest

on:
  pull_request:
    branches:
      - main-source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Pull scripts
        run: sudo make pull-scripts

      - name: Pull in all relevant branches
        run: git fetch origin main-source main
      
      - name: Validate 
        run: sudo make validate
